# Generated by Django 4.0.2 on 2022-02-20 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Officials',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('official_gmail', models.EmailField(max_length=255, unique=True)),
                ('official_account', models.CharField(default='', max_length=255, unique=True)),
                ('available_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('blockchain_address', models.CharField(default='', max_length=255, unique=True)),
                ('kyc_done', models.BooleanField(default=False)),
                ('official_appointed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pending', models.BooleanField(default=True)),
                ('meetlink', models.CharField(max_length=40, null=True)),
                ('meetingTime', models.DateTimeField()),
                ('official', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.officials')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
    ]
