# Generated by Django 3.2.9 on 2022-01-18 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Officials',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('official_gmail', models.EmailField(max_length=255, unique=True)),
                ('available_time', models.DateTimeField()),
            ],
        ),
    ]
