# Generated by Django 3.2.9 on 2022-01-18 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_officials'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='official_assigned',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.officials'),
        ),
    ]
