# Generated by Django 3.2.9 on 2022-02-08 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20220208_1407'),
    ]

    operations = [
        migrations.RenameField(
            model_name='officials',
            old_name='blockchain_address',
            new_name='official_account',
        ),
    ]
