# Generated by Django 3.2.9 on 2022-02-10 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_blockchain_address_officials_official_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='code',
        ),
        migrations.AddField(
            model_name='meeting',
            name='meetlink',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='pending',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='official',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.officials'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
    ]
