# Generated by Django 3.2.9 on 2022-02-12 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20220212_1514'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='time',
            new_name='meetingTime',
        ),
    ]
